chain:
    bech32_prefix: animus
    modules: []
node:
    type: remote
    config:
        rpc:
            client_name: juno
            address: http://localhost:26657
            max_connections: 20
        grpc:
            address: localhost:9090
            insecure: true
parsing:
    workers: 1
    listen_new_blocks: true
    parse_old_blocks: true
    parse_genesis: true
    start_height: 1
    average_block_time: 10s
database:
    name: bdjuno
    host: localhost
    port: 5432
    user: bdjuno
    password: bdjuno
    schema: public
    max_open_connections: 1
    max_idle_connections: 1
    partition_size: 100000
    partition_batch: 1000
logging:
    level: info
    format: text
actions:
    port: 3000
